// <auto-generated />
using System;
using MagicVilla_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SquareMetres")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            Capacity = 8,
                            CreationDate = new DateTime(2024, 1, 28, 17, 32, 54, 744, DateTimeKind.Local).AddTicks(3009),
                            Detail = "Increible",
                            ImgageUrl = "",
                            Name = "Villa Real",
                            Price = 200.0,
                            SquareMetres = 90,
                            UpdateDate = new DateTime(2024, 1, 28, 17, 32, 54, 744, DateTimeKind.Local).AddTicks(3019)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            Capacity = 6,
                            CreationDate = new DateTime(2024, 1, 28, 17, 32, 54, 744, DateTimeKind.Local).AddTicks(3021),
                            Detail = "Con icreible vista a la gran piscina",
                            ImgageUrl = "",
                            Name = "Villa Olimpica",
                            Price = 100.0,
                            SquareMetres = 70,
                            UpdateDate = new DateTime(2024, 1, 28, 17, 32, 54, 744, DateTimeKind.Local).AddTicks(3021)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
